### ISSUE TITLE
Case class with several similar `apply` functions

### ISSUE THREAD

**Issue by mr-git** [playframework/play-json#73]
I tried to upgrade from "2.5.14" to "2.6.0" and stumbled on interesting issue when case class has several similar `apply` functions.

```
package xxx

import play.api.libs.json.{Json, OFormat}

case class XXX(xxx: String, age: Int)

object XXX {
  implicit val XxxFormat: OFormat[XXX] = Json.format[XXX]
}
```

Compiles fine, until one adds second `apply` function like:
```
  def apply(xxx: String, age: Option[Int]): XXX = XXX(xxx, age getOrElse 21)
```

When above code is added in companion object, I am getting warning: 
```
Warning:(8, 53) Type parameters are not matching: Option[Int] != Int
  implicit val XxxFormat: OFormat[XXX] = Json.format[XXX]
```

In our project we have many such places which are working fine with "2.5.14", and we have enabled `"-Xfatal-warnings"` in scalac options - this option promotes this warning to compilation error.

What is suggested way to migrate such code to 2.6.0 version? 
Maybe I am doing something wrong here?

**Comment by mr-git** [comment]
What is interesting - problem is only similar `apply` functions, like:
```
  apply(xxx: String): XXX = XXX(xxx, 21) // compiles OK
  apply(age: Int): XXX = XXX("xxx", age) // compiles OK
```

Problem starts with "similar" arguments, where similar means "wrapped in `Option`", like `Int` is similar with `Option[Int]`.
