### ISSUE TITLE
`JsBoolean.unapply` change is binary incompatible

### ISSUE THREAD

**Issue by zkerriga** [playframework/play-json#1357]
The change of `JsBoolean.unapply` return type introduced in https://github.com/playframework/play-json/pull/1173 is binary incompatible.

When the library compiled with `3.0.6` uses the method, while `3.1.0-M2` is in the classpath, the JVM reports:
```
java.lang.NoSuchMethodError: 'scala.Option play.api.libs.json.JsBoolean$.unapply(play.api.libs.json.JsBoolean)'
```

**Comment by mkurz** [comment]
PR welcome

**Comment by zkerriga** [comment]
I can create a PR with a revert of the change. Would that be ok?

**Comment by mkurz** [comment]
Lets wait what @xuwei-k says

**Comment by xuwei-k** [comment]
What is the binary compatibility policy between 3.0.x to 3.1.x?
I have broken binary compatibility on purpose in https://github.com/playframework/play-json/pull/1173.

**Comment by mkurz** [comment]
ah yeah sorry, we can break compatibily.
so this is not an issue.

**Comment by mr-git** [comment]
Just wondering, why `play-json` doesn't have following in `build.sbt`?:
```
ThisBuild / versionScheme := Some("pvp")
```
